# This is a basic workflow to help you get started with Actions

name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: php-actions/composer@v1
      - uses: education/autograding@v1
